/**
 * Test script for the file manager
 * 
 * This script tests the createSiteDirectory and saveSiteFiles functions
 */

import { createSiteDirectory, saveSiteFiles } from '../../src/managers/fileManager.js';
import path from 'path';

async function testFileManager() {
  console.log('Testing file manager...');
  
  try {
    // Test base directory
    const baseDir = path.resolve(process.cwd(), 'test-output');
    
    // Test site name with special characters to test sanitization
    const siteName = 'Test Site Name! @#$%';
    
    // Test content
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test HTML</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>Test File Manager</h1>
  <p>This is a test file generated by the file manager test script.</p>
</body>
</html>`;

    const cssContent = `body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 20px;
  background-color: #f5f5f5;
}

h1 {
  color: #333;
}`;

    // Create the directory
    console.log(`Creating directory for site: ${siteName}`);
    const dirPath = await createSiteDirectory(baseDir, siteName);
    
    // Save the files
    console.log('Saving site files...');
    await saveSiteFiles(dirPath, htmlContent, cssContent);
    
    console.log(`Test completed successfully! Check files at: ${dirPath}`);
  } catch (error) {
    console.error('Test failed:', error);
  }
}

// Run the test
testFileManager(); 